spring.application.name=GGarciaProgramacionNCapasMavenCliente
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-parameters=10000
server.tomcat.max-part-count=10000
server.port=8080

# URL base del proyecto de servicios (GGarciaProgramacionNCapasMavenServices)
services.base-url=http://localhost:8081

# Endpoints consumidos desde el cliente
services.endpoints.usuario=/api/usuario
services.endpoints.rol=/api/rol
services.endpoints.pais=/api/pais
services.endpoints.direccion=/api/direccion


